### ISSUE TITLE
Sudden bluetooth error?

### ISSUE THREAD

**Issue by viewsonic1337** [philipfong/auto-vaccine-appointment#5]
I used this to book my parents a month back! Worked great! Went to book myself but damn captchas!

I see you updated to fix this though. I loaded the new files but now I get this error

"Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed."

**Comment by viewsonic1337** [comment]
I waited about 5 minutes and it actually ends up running!

It seems on the pages that it wants to prove I am not a robot, it just closes it and starts over.

**Comment by philipfong** [comment]
@viewsonic1337 I'm so glad to hear that it helped out. That's very, very cool that it automated its way from start to finish for you.

The captcha requests on the NYS site are pretty aggressive so I don't plan on continuing this project much longer. The recent changes I made were designed to work more as a hacked up 'page refresher'. Running `rspec spec/features/book_vaccine.rb:19` allows you to run code based on line number if you are interested in what that might look like. The code is very raw so you'll want to experiment on your own. From personal experience, I did succeed in grabbing one of the few J&J spots at Javitz for my wife.

I've also found the NYS site to be really buggy. There are definitely appointments that show up at locations that say 'No Appointments Available'. Some locations present a captcha while others do not. It's really luck of the draw at this point and no amount of code is going to succeed on something so incredibly flaky.

**Comment by viewsonic1337** [comment]
Thank you for all your work though! I got both my parents last month with this.

I am located on long island so only 2 locations. Yesterday only ONE location presented a capthca! Now they BOTH do. ugh. 

I always wonder why they never had a captcha, now they have one and It sucks! haha.

Manually trying to book for my wife and myslef is almost IMPOSSIBLE.

**Comment by philipfong** [comment]
Hang in there, I have a feeling things will open up at the pharmacies more quickly than we think. I'm very happy to hear that your folks were taken care of.

If I can spare some time, I'll try and see if there are workarounds to the captchas or at least have users manually intervene so the script can continue.
